[package]
authors = ["kngwyu <yuji.kngw.80s.revive@gmail.com>"]
name = "sa_test"
version = "0.1.0"
[dependencies]
lazy_static = "0.2.8"
piston_window = "0.67.0"
rand = "0.3.15"
slog = "2.0.6"
sloggers = "0.2.0"

[dependencies.clap]
features = ["yaml"]
version = "2.26"
